package br.ufes.informatica.webhealth.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Doenca extends PersistentObjectSupport implements Comparable<Doenca> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 50)
	private String nomeDoenca;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	private Long idDoenca;

	/** TODO: generated by FrameWeb. Should be documented. */
	@OneToMany(mappedBy = "doenca")
	private Set<Ocorrencia> ocorrencias;

	/** Getter for nomeDoenca. */
	public String getNomeDoenca() {
		return nomeDoenca;
	}

	/** Setter for nomeDoenca. */
	public void setNomeDoenca(String nomeDoenca) {
		this.nomeDoenca = nomeDoenca;
	}

	/** Getter for idDoenca. */
	public Long getIdDoenca() {
		return idDoenca;
	}

	/** Setter for idDoenca. */
	public void setIdDoenca(Long idDoenca) {
		this.idDoenca = idDoenca;
	}

	/** Getter for Source. */
	public Set<Ocorrencia> getOcorrencia() {
		return ocorrencias;
	}

	/** Setter for Source. */
	public void setSource(Set<Ocorrencia> ocorrencias) {
		this.ocorrencias = ocorrencias;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Doenca o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}