package br.ufes.informatica.webhealth.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Ocorrencia extends PersistentObjectSupport implements Comparable<Ocorrencia> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 300)
	private String descricaoTratamento;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Doenca doenca;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToOne
	private Paciente paciente;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(fetch=FetchType.EAGER)
	private Set<Remedio> remedios = new HashSet<Remedio>();

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany(fetch=FetchType.EAGER)
	private Set<Sintoma> sintomas = new HashSet<Sintoma>();

	/** Getter for descricaoTratamento. */
	public String getDescricaoTratamento() {
		return descricaoTratamento;
	}

	/** Setter for descricaoTratamento. */
	public void setDescricaoTratamento(String descricaoTratamento) {
		this.descricaoTratamento = descricaoTratamento;
	}

	/** Getter for Target. */
	public Doenca getDoenca() {
		return doenca;
	}

	/** Setter for Target. */
	public void setDoenca(Doenca doenca) {
		this.doenca = doenca;
	}
	
	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/** Getter for Source. */
	public Paciente getPaciente() {
		return paciente;
	}

	/** Getter for Source. */
	public Set<Remedio> getRemedios() {
		return remedios;
	}

	/** Setter for Source. */
	public void setRemedios(Set <Remedio> remedios) {
		this.remedios = remedios;
	}

	/** Getter for Source. */
	public Set<Sintoma> getSintomas() {
		return sintomas;
	}

	/** Setter for Source. */
	public void setSintomas(Set<Sintoma> sintomas) {
		this.sintomas = sintomas;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Ocorrencia o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}