package br.ufes.informatica.webhealth.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Ocorrencia extends PersistentObjectSupport implements Comparable<Ocorrencia> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 300) 
	private String descricaoTratamento;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private List remedios;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	public Long idOcorrencia;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private List sintomas;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Doenca Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Paciente Source;
		
	




	/** Getter for descricaoTratamento. */
	public String getDescricaoTratamento() {
		return descricaoTratamento;
	}
	
	/** Setter for descricaoTratamento. */
	public void setDescricaoTratamento(String descricaoTratamento) {
		this.descricaoTratamento = descricaoTratamento;
	}

	/** Getter for remedios. */
	public List getRemedios() {
		return remedios;
	}
	
	/** Setter for remedios. */
	public void setRemedios(List remedios) {
		this.remedios = remedios;
	}

	/** Getter for idOcorrencia. */
	public Long getIdOcorrencia() {
		return idOcorrencia;
	}
	
	/** Setter for idOcorrencia. */
	public void setIdOcorrencia(Long idOcorrencia) {
		this.idOcorrencia = idOcorrencia;
	}

	/** Getter for sintomas. */
	public List getSintomas() {
		return sintomas;
	}
	
	/** Setter for sintomas. */
	public void setSintomas(List sintomas) {
		this.sintomas = sintomas;
	}




		
		/** Getter for Target. */
		public Doenca getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Doenca Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Paciente getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Paciente Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Ocorrencia o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}