package br.ufes.informatica.webhealth.core.domain;

import java.util.List;

import javax.persistence.Entity;
import javax.validation.constraints.NotNull;

import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Paciente extends PersistentObjectSupport implements Comparable<Paciente> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private Long idPaciente;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String sexo;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String endereco;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String cidade;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String estado;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private List<Doenca> doencas;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String login;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String senha;

	/** Getter for nome. */
	public String getNome() {
		return nome;
	}

	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for idPaciente. */
	public Long getIdPaciente() {
		return idPaciente;
	}

	/** Setter for idPaciente. */
	public void setIdPaciente(Long idPaciente) {
		this.idPaciente = idPaciente;
	}

	/** Getter for sexo. */
	public String getSexo() {
		return sexo;
	}

	/** Setter for sexo. */
	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	/** Getter for endereco. */
	public String getEndereco() {
		return endereco;
	}

	/** Setter for endereco. */
	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	/** Getter for cidade. */
	public String getCidade() {
		return cidade;
	}

	/** Setter for cidade. */
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	/** Getter for estado. */
	public String getEstado() {
		return estado;
	}

	/** Setter for estado. */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/** Getter for doencas. */
	public List getDoencas() {
		return doencas;
	}

	/** Setter for doencas. */
	public void setDoencas(List<Doenca> doencas) {
		this.doencas = doencas;
	}

	/** Getter for login. */
	public String getLogin() {
		return login;
	}

	/** Setter for login. */
	public void setLogin(String login) {
		this.login = login;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}

	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Paciente o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}