package br.ufes.informatica.webhealth.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Remedio extends PersistentObjectSupport implements Comparable<Remedio> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull @Size(max = 50) 
	private String nomeRemedio;

	/** TODO: generated by FrameWeb. Should be documented. */
	//@ManyToMany
	//private Set<Ocorrencia> ocorrencias;

	/** Getter for nomeRemedio. */
	public String getNomeRemedio() {
		return nomeRemedio;
	}
	
	/** Setter for nomeRemedio. */
	public void setNomeRemedio(String nomeRemedio) {
		this.nomeRemedio = nomeRemedio;
	}




		
		/** Getter for Target. */
		//public Set<Ocorrencia> getOcorrencias() {
		//	return ocorrencias;
		//}
		
		/** Setter for Target. */
		//public void setTarget(Set<Ocorrencia> ocorrencias) {
		//	this.ocorrencias = ocorrencias;
		//}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Remedio o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}