package br.ufes.informatica.webhealth.core.domain;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Sintoma extends PersistentObjectSupport implements Comparable<Sintoma> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull
	@Size(max = 50)
	private String descricaoSintoma;

	/** TODO: generated by FrameWeb. Should be documented. */
	@ManyToMany
	private Set<Ocorrencia> ocorrencias;

	/** Getter for descricaoSintoma. */
	public String getDescricaoSintoma() {
		return descricaoSintoma;
	}

	/** Setter for descricaoSintoma. */
	public void setDescricaoSintoma(String descricaoSintoma) {
		this.descricaoSintoma = descricaoSintoma;
	}

	/** Getter for Target. */
	public Set<Ocorrencia> getOcorrencias() {
		return ocorrencias;
	}

	/** Setter for Target. */
	public void setTarget(Set<Ocorrencia> ocorrencias) {
		this.ocorrencias = ocorrencias;
	}

	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Sintoma o) {
		// FIXME: auto-generated method stub
		return super.compareTo(o);
	}
}