package br.ufes.informatica.webhealth.core.controller;

import java.io.Serializable;

import javax.ejb.Local;

import br.ufes.informatica.webhealth.core.domain.Ocorrencia;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CadastroOcorrenciaService extends Serializable {

	/** TODO: generated by FrameWeb. Should be documented. */
	public Boolean salvaOcorrencia(Ocorrencia ocorrencia);

}