package br.ufes.informatica.webhealth.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.webhealth.core.application.CadastroOcorrenciaService;
import br.ufes.informatica.webhealth.core.domain.Ocorrencia;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CadastroOcorrenciaController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CadastroOcorrenciaService cadastroOcorrenciaService;
	

	/** TODO: generated by FrameWeb. Should be documented. */
	private Ocorrencia ocorrencia;

	public CadastroOcorrenciaController() {
		this.ocorrencia= new Ocorrencia();
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String salvaOcorrencia() {
		// FIXME: auto-generated method stub
		return null;
	}

	/** Getter for ocorrencia. */
	public Ocorrencia getOcorrencia() {
		return ocorrencia;
	}

	/** Setter for ocorrencia. */
	public void setOcorrencia(Ocorrencia ocorrencia) {
		this.ocorrencia = ocorrencia;
	}

}