package br.ufes.informatica.webhealth.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.webhealth.core.domain.Paciente;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CadastroPacienteController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CadastroPacienteService cadastroPacienteService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private Paciente paciente;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String confirmaSenha;

	/** Getter for paciente. */
	public Paciente getPaciente() {
		return paciente;
	}

	/** Setter for paciente. */
	public void setPaciente(Paciente paciente) {
		this.paciente = paciente;
	}

	/** Getter for confirmaSenha. */
	public String getConfirmaSenha() {
		return confirmaSenha;
	}

	/** Setter for confirmaSenha. */
	public void setConfirmaSenha(String confirmaSenha) {
		this.confirmaSenha = confirmaSenha;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String cadastrar() {
		// FIXME: auto-generated method stub
		return null;
	}

}