package br.ufes.informatica.webhealth.core.controller;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.inject.*;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.inf.nemo.jbutler.ejb.controller.CrudController;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.webhealth.core.application.CadastroPacienteService;
import br.ufes.informatica.webhealth.core.domain.Ocorrencia;
import br.ufes.informatica.webhealth.core.domain.Paciente;


/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CadastroPacienteController extends CrudController<Paciente> {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private CadastroPacienteService cadastroPacienteService;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String confirmaSenha;
	
	
	/** Getter for confirmaSenha. */
	public String getConfirmaSenha() {
		return confirmaSenha;
	}

	/** Setter for confirmaSenha. */
	public void setConfirmaSenha(String confirmaSenha) {
		this.confirmaSenha = confirmaSenha;
	}


	@Override
	protected CrudService<Paciente> getCrudService() {
		// TODO Auto-generated method stub
		return cadastroPacienteService;
	}



	@Override
	protected void initFilters() {
		// TODO Auto-generated method stub
		
	}
	

	public String voltar()
	{
		return "/core/login/logi.xhtml?faces-redirect=true";
	}
	
}