package br.ufes.informatica.webhealth.core.controller;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class FiltroServiceBean implements FiltroService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private OcorrenciaDAO ocorrenciaDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public List filtrar(List doencas, String cidade, List sintomas, String estado, List remedios) {
		// FIXME: auto-generated method stub
		return null;
	}
	
}