package br.ufes.informatica.webhealth.core.controller;

import java.util.List;

import javax.ejb.EJB;

import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.webhealth.core.application.FiltroService;
import br.ufes.informatica.webhealth.core.domain.Doenca;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class FiltroController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private FiltroService filtroService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<Doenca> doencas;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<String> sintomas;

	/** TODO: generated by FrameWeb. Should be documented. */
	private List<String>  remedios;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String cidade;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String estado;

	/** Getter for doencas. */
	public List getDoencas() {
		return doencas;
	}

	/** Setter for doencas. */
	public void setDoencas(List<Doenca> doencas) {
		this.doencas = doencas;
	}

	/** Getter for sintomas. */
	public List getSintomas() {
		return sintomas;
	}

	/** Setter for sintomas. */
	public void setSintomas(List<String>  sintomas) {
		this.sintomas = sintomas;
	}

	/** Getter for remedios. */
	public List<String> getRemedios() {
		return remedios;
	}

	/** Setter for remedios. */
	public void setRemedios(List<String>  remedios) {
		this.remedios = remedios;
	}

	/** Getter for cidade. */
	public String getCidade() {
		return cidade;
	}

	/** Setter for cidade. */
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	/** Getter for estado. */
	public String getEstado() {
		return estado;
	}

	/** Setter for estado. */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public List filtrar() {
		// FIXME: auto-generated method stub
		return null;
	}

}