package br.ufes.informatica.webhealth.core.controller;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface FiltroService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List filtrar(List doencas, String cidade, List sintomas, String estado, List remedios);
	
}