package br.ufes.informatica.webhealth.core.controller;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.*;
import javax.inject.Named;

import org.apache.jena.datatypes.RDFDatatype;
import org.apache.jena.query.QueryExecution;
import org.apache.jena.query.QueryExecutionFactory;
import org.apache.jena.query.QuerySolution;
import org.apache.jena.query.ResultSet;
import org.apache.jena.rdf.model.Literal;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;
import br.ufes.informatica.webhealth.core.application.LoginService;
import br.ufes.informatica.webhealth.core.domain.Paciente;

/** TODO: generated by FrameWeb. Should be documented. */
@Named
@SessionScoped
public class LoginController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	private String name;
	private String description;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private LoginService loginService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String login;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String senha;

	/** TODO: generated by FrameWeb. Should be documented. */
	public String realizarLogin() {
		try {
			Paciente paciente = loginService.realizarLogin(this.login, this.senha);
			if (paciente == null) {
				return "/login/error?faces-redirect=true";
			} else {
				getExternalContext().getSessionMap().put("paciente", paciente);
				return "/core/dashboard/index?faces-redirect=true";
			}
		} catch (Exception e) {
			return "/login/error?faces-redirect=true";
		}

	}

	public String desconectar() {
		getExternalContext().getSessionMap().remove("paciente");
		return "/index?faces-redirect=true";
	}

	public Paciente getPaciente() {
		return (Paciente) getExternalContext().getSessionMap().get("paciente");
	}

	/** Getter for login. */
	public String getLogin() {
		return login;
	}

	/** Setter for login. */
	public void setLogin(String login) {
		this.login = login;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}

	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String irParaCadastro() {
		return "/cadastroPaciente/index.xhtml?faces-redirect=true";
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}