package br.ufes.informatica.webhealth.core.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.Model;

import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class LoginController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private LoginService loginService;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String login;

	/** TODO: generated by FrameWeb. Should be documented. */
	private String senha;

	/** Getter for login. */
	public String getLogin() {
		return login;
	}

	/** Setter for login. */
	public void setLogin(String login) {
		this.login = login;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}

	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	public String realizarLogin() {
		// FIXME: auto-generated method stub
		return null;
	}

}