package br.ufes.informatica.webhealth.core.persistence;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface DoencaDAO extends BaseDAO<Doenca> {
	
}