package br.ufes.informatica.webhealth.core.persistence;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.webhealth.core.domain.Ocorrencia;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OcorrenciaDAO extends BaseDAO<Ocorrencia> {
	
}