package br.ufes.informatica.webhealth.core.persistence;

import java.util.List;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.webhealth.core.domain.Doenca;
import br.ufes.informatica.webhealth.core.domain.Ocorrencia;
import br.ufes.informatica.webhealth.core.domain.Remedio;
import br.ufes.informatica.webhealth.core.domain.Sintoma;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface OcorrenciaDAO extends BaseDAO<Ocorrencia> {
	public List<Ocorrencia> filtrar(List<String> doencas, String cidade, String estado);
	public List<Ocorrencia> listarOcorrencias();
}