package br.ufes.informatica.webhealth.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.webhealth.core.domain.Paciente;
import br.ufes.informatica.webhealth.core.domain.Paciente_;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PacienteJPADAO extends BaseJPADAO<Paciente> implements PacienteDAO{
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
    @PersistenceContext
    private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}
    
    
	/** TODO: generated by FrameWeb. Should be documented. */
    @Override
	public Paciente realizarLogin(String login, String senha) {
    	CriteriaBuilder cb = entityManager.getCriteriaBuilder();
		CriteriaQuery<Paciente> cq = cb.createQuery(Paciente.class);
		Root<Paciente> root = cq.from(Paciente.class);
		cq.where(cb.equal(cb.lower(root.get(Paciente_.login)),login.toLowerCase()),cb.equal(cb.lower(root.get(Paciente_.senha)),senha.toLowerCase()));
		return entityManager.createQuery(cq).getSingleResult();
	}
	

}