package br.ufes.informatica.webhealth.core.persistence;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseJPADAO;
import br.ufes.informatica.webhealth.core.domain.Paciente;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class PacienteJPADAO extends BaseJPADAO<Paciente> implements PacienteDAO {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	/** TODO: generated by FrameWeb. Should be documented. */
	@PersistenceContext
	private EntityManager entityManager;

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	protected EntityManager getEntityManager() {
		return entityManager;
	}

	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Boolean realizarLogin() {
		// FIXME: auto-generated method stub
		return null;
	}

}