package br.ufes.informatica.webhealth.core.persistence;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.webhealth.core.domain.Doenca;
import br.ufes.informatica.webhealth.core.domain.Remedio;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface RemedioDAO extends BaseDAO<Remedio> {
	
}