package br.ufes.informatica.webhealth.core.persistence;

import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.webhealth.core.domain.Sintoma;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface SintomaDAO extends BaseDAO<Sintoma> {
	
}