package br.ufes.informatica.webhealth.core.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.informatica.webhealth.core.domain.Paciente;
import br.ufes.informatica.webhealth.core.persistence.PacienteDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CadastroPacienteServiceBean implements CadastroPacienteService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PacienteDAO pacienteDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Boolean cadastrar(Paciente paciente) {
		// FIXME: auto-generated method stub
		return null;
	}
	
}