package br.ufes.informatica.webhealth.core.application;

import java.util.List;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudException;
import br.ufes.inf.nemo.jbutler.ejb.application.CrudServiceBean;
import br.ufes.inf.nemo.jbutler.ejb.application.filters.Filter;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;
import br.ufes.informatica.webhealth.core.domain.Paciente;
import br.ufes.informatica.webhealth.core.persistence.PacienteDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class CadastroPacienteServiceBean extends CrudServiceBean<Paciente> implements CadastroPacienteService {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private PacienteDAO pacienteDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public Boolean cadastrar(Paciente paciente) {
		// FIXME: auto-generated method stub
		return null;
	}







	@Override
	public void validateCreate(Paciente entity) throws CrudException {
		// TODO Auto-generated method stub
		
	}







	@Override
	public void validateUpdate(Paciente entity) throws CrudException {
		// TODO Auto-generated method stub
		
	}







	@Override
	public void validateDelete(Paciente entity) throws CrudException {
		// TODO Auto-generated method stub
		
	}







	@Override
	public void create(Paciente entity) {
		// TODO Auto-generated method stub
		
	}







	@Override
	public Paciente retrieve(Long id) {
		// TODO Auto-generated method stub
		return null;
	}







	@Override
	public void update(Paciente entity) {
		// TODO Auto-generated method stub
		
	}







	@Override
	public void delete(Paciente entity) {
		// TODO Auto-generated method stub
		
	}







	@Override
	public BaseDAO<Paciente> getDAO() {
		// TODO Auto-generated method stub
		return null;
	}







	@Override
	public void authorize() {
		// TODO Auto-generated method stub
		
	}







	@Override
	public long count() {
		// TODO Auto-generated method stub
		return 0;
	}







	@Override
	public long countFiltered(Filter<?> filterType, String filter) {
		// TODO Auto-generated method stub
		return 0;
	}







	@Override
	public List<Paciente> list(int... interval) {
		// TODO Auto-generated method stub
		return null;
	}







	@Override
	public List<Paciente> filter(Filter<?> filter, String filterParam, int... interval) {
		// TODO Auto-generated method stub
		return null;
	}







	@Override
	public Paciente fetchLazy(Paciente entity) {
		// TODO Auto-generated method stub
		return null;
	}
	
}