package br.ufes.informatica.webhealth.core.application;

import java.io.Serializable;
import javax.ejb.Local;

import br.ufes.inf.nemo.jbutler.ejb.application.CrudService;
import br.ufes.informatica.webhealth.core.domain.Paciente;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface CadastroPacienteService extends CrudService<Paciente> {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Boolean cadastrar(Paciente paciente);
	
}