package br.ufes.informatica.webhealth.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.webhealth.core.domain.Doenca;
import br.ufes.informatica.webhealth.core.domain.Ocorrencia;
import br.ufes.informatica.webhealth.core.domain.Remedio;
import br.ufes.informatica.webhealth.core.domain.Sintoma;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface FiltroService extends Serializable {

	public List<Ocorrencia> filtrarPorRemedios(List<Remedio> remedios, String cidade, String estado);

	public List<Ocorrencia> filtrarPorSintomas(List<Sintoma> sintomas, String cidade, String estado);

	public List<Ocorrencia> filtrarPorDoenças(List<String> doencas, String cidade, String estado);

}