package br.ufes.informatica.webhealth.core.application;

import java.io.Serializable;
import java.util.List;

import javax.ejb.Local;

import br.ufes.informatica.webhealth.core.domain.Doenca;
import br.ufes.informatica.webhealth.core.domain.Ocorrencia;
import br.ufes.informatica.webhealth.core.domain.Remedio;
import br.ufes.informatica.webhealth.core.domain.Sintoma;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface FiltroService extends Serializable {

	public List<Ocorrencia> filtrar(List<String> doencas, String cidade,
			List<Sintoma> sintomas, String estado,
			List<Remedio> remedios);


	
}