package br.ufes.informatica.webhealth.core.application;

import java.io.Serializable;
import javax.ejb.Local;

import br.ufes.informatica.webhealth.core.domain.Paciente;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface LoginService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public Paciente realizarLogin(String login, String Senha);	
	
}